const DATA_URL="outputs/interviewdb-amazon-questions-2026-09-01/amazon_interview_questions_no_oa_phone_or_onsite.csv";
const STORAGE_KEY="algoatlas-amazon-completed-v1";
const TAG_OVERRIDES={
"destination-cache":["Hash Map","Linked List","LRU Cache","Design"],"gold-thief":["Arrays","Dynamic Programming"],"block-words":["Strings","Backtracking"],"character-separation":["Strings","Greedy"],"common-manager":["Trees","Lowest Common Ancestor","Design"],"conversion-rate":["Graphs","DFS","Weighted Graph"],"delivery-time":["Heap","Data Stream"],"query-builder":["LLD","Object-Oriented Design","Composite Pattern"],"raffle-winners":["Greedy","Simulation"],"top-visit-sequence":["Hash Map","Sequences"],"tree-kyoukai":["Trees","DFS"],"word-decomposition":["Strings","Dynamic Programming","Trie"],"xo-game":["Matrix","Design","Simulation"],"course-completion":["Graphs","Topological Sort","DFS"],"increment-one":["Linked List","Math"],"jihanki-network":["System Design","Distributed Systems"],"number-of-paths":["Grid","Dynamic Programming"],"streak-number":["Hash Map","Data Stream"],"top-customers":["Hash Map","Heap"],"vm-load":["Scheduling","Greedy","Heap"],"asin-average-price":["Hash Map","Aggregation"],"cloudwatch":["System Design","Distributed Systems","Logging"],"config-distribution":["System Design","Distributed Systems","Pub/Sub"],"config-manager":["LLD","Object-Oriented Design"],"discount":["LLD","Strategy Pattern","Object-Oriented Design"],"distributed-sort-softmax":["External Sort","Distributed Systems","Machine Learning"],"employee-directory":["Object-Oriented Design","Trees"],"financial-dashboard":["System Design","Data Modeling"],"food-delivery":["System Design","Distributed Systems"],"friendship-path":["Graphs","BFS"],"friends-purchases":["Graphs","Hash Map"],"fulfillment":["Graphs","Shortest Path"],"merge-interval":["Intervals","Sorting"],"non-returning-users":["Hash Map","Set"],"package-installation":["Graphs","Topological Sort","Design"],"playlist":["Linked List","Design"],"rate-limiter":["LLD","Rate Limiting","Sliding Window"],"sawtooth-pattern-string-builder":["Strings","Simulation"],"shima":["Grid","DFS","Union Find"],"shipping-cost":["LLD","Strategy Pattern"],"spell-checker":["Trie","Strings","LLD"],"usage-tracker":["LLD","Data Stream"],"validation-framework":["LLD","Composite Pattern"],"word-trail":["Strings","Dynamic Programming","Trie"]};

const storedProgress=localStorage.getItem(STORAGE_KEY);
const state={questions:[],completed:new Set(storedProgress?JSON.parse(storedProgress):[]),selectedId:null,stage:"All",topics:new Set(),query:"",hideDone:false,sort:"frequency",loading:true};
const el=id=>document.getElementById(id);let toastTimer;

document.addEventListener("DOMContentLoaded",async()=>{bindEvents();setLoading(true);try{await loadQuestions()}catch(error){console.error(error);el("loading-state").textContent="Could not load the question set."}finally{state.loading=false;setLoading(false);render()}});

async function loadQuestions(){const response=await fetch(DATA_URL);if(!response.ok)throw new Error(`Question data returned ${response.status}`);const rows=parseCsv(await response.text());state.questions=rows.map(row=>{const id=(row.question_url.split("/").filter(Boolean).pop()||slugify(row.title));const baseTags=row.tags.split("|").map(tag=>tag.trim()).filter(Boolean);return{id,rank:Number(row.global_rank),title:row.title,baseTags,tags:inferTags(id,row.title,row.question_description,baseTags),frequency:Number(row.frequency_percent),lastReported:row.last_reported||"Date unavailable",description:row.question_description,url:row.question_url,importedDone:row.completed==="true"}});if(!storedProgress){state.questions.filter(q=>q.importedDone).forEach(q=>state.completed.add(q.id));persistProgress()}const hashId=location.hash.replace(/^#question=/,"");state.selectedId=state.questions.some(q=>q.id===hashId)?hashId:state.questions[0]?.id||null}

function parseCsv(text){const rows=[];let row=[],cell="",quoted=false;for(let i=0;i<text.length;i++){const c=text[i];if(quoted){if(c==='"'&&text[i+1]==='"'){cell+='"';i++}else if(c==='"')quoted=false;else cell+=c}else if(c==='"')quoted=true;else if(c===","){row.push(cell);cell=""}else if(c==="\n"){row.push(cell);rows.push(row);row=[];cell=""}else if(c!=="\r")cell+=c}if(cell||row.length){row.push(cell);rows.push(row)}const headers=rows.shift()||[];return rows.filter(r=>r.some(Boolean)).map(values=>Object.fromEntries(headers.map((h,i)=>[h,values[i]??""])))}

function inferTags(id,title,description,baseTags){const text=`${title} ${description}`.toLowerCase(),tags=new Set(baseTags);if(baseTags.includes("Low Level Design")){tags.add("LLD");tags.add("Object-Oriented Design")}if(baseTags.includes("System Design"))tags.add("System Design");if(baseTags.includes("MLE"))tags.add("Machine Learning");if(/binary tree|\btree\b|hierarch|manager/.test(text))tags.add("Trees");if(/graph|network|friend|prerequisite|dependenc/.test(text))tags.add("Graphs");if(/linked list/.test(text))tags.add("Linked List");if(/string|word|character|spell|filename|text/.test(text))tags.add("Strings");if(/array|interval|matrix|grid|sequence|\blist\b/.test(text))tags.add("Arrays");if(/cache|hash|lookup|directory|frequency|count the number/.test(text))tags.add("Hash Map");if(/median|priority|most frequent|top n|highest/.test(text))tags.add("Heap");if(/sort|sorted|ascending order|ranking/.test(text))tags.add("Sorting");if(/interval|overlap/.test(text))tags.add("Intervals");if(/minimum|maximum|optimal|number of paths/.test(text))tags.add("Dynamic Programming");if(/design|implement a class|interface|framework/.test(text))tags.add("Design");(TAG_OVERRIDES[id]||[]).forEach(tag=>tags.add(tag));return [...tags]}

function bindEvents(){el("stage-filters").addEventListener("click",event=>{const button=event.target.closest("[data-stage]");if(!button)return;state.stage=button.dataset.stage;document.querySelectorAll("[data-stage]").forEach(item=>item.classList.toggle("active",item===button));render()});el("search-input").addEventListener("input",event=>{state.query=event.target.value.trim().toLowerCase();render()});el("sort-select").addEventListener("change",event=>{state.sort=event.target.value;render()});el("hide-done-button").addEventListener("click",event=>{state.hideDone=!state.hideDone;event.currentTarget.setAttribute("aria-pressed",String(state.hideDone));render()});["detail-done-button","detail-done-footer"].forEach(id=>el(id).addEventListener("click",()=>toggleDone(state.selectedId)));el("previous-question").addEventListener("click",()=>moveSelection(-1));el("next-question").addEventListener("click",()=>moveSelection(1));el("clear-topics").addEventListener("click",()=>{state.topics.clear();render()});document.addEventListener("keydown",event=>{if(event.target.matches("input,select,textarea"))return;if(event.key.toLowerCase()==="j")moveSelection(1);if(event.key.toLowerCase()==="k")moveSelection(-1)})}
function setLoading(loading){el("loading-state").classList.toggle("hidden",!loading);el("question-list").classList.toggle("hidden",loading)}
function filtered(){const out=state.questions.filter(q=>{const text=`${q.title} ${q.tags.join(" ")} ${q.description}`.toLowerCase();return(state.stage==="All"||q.baseTags.includes(state.stage))&&(!state.query||text.includes(state.query))&&(state.topics.size===0||[...state.topics].every(tag=>q.tags.includes(tag)))&&(!state.hideDone||!state.completed.has(q.id))});return out.sort((a,b)=>state.sort==="title"?a.title.localeCompare(b.title):state.sort==="unfinished"?Number(state.completed.has(a.id))-Number(state.completed.has(b.id))||b.frequency-a.frequency:b.frequency-a.frequency||a.rank-b.rank)}
function render(){renderTopics();renderList();renderDetail();renderProgress()}
function renderTopics(){const reserved=new Set(["Coding","Phone","Onsite","Low Level Design","System Design","MLE"]),counts=new Map();state.questions.forEach(q=>q.tags.filter(tag=>!reserved.has(tag)).forEach(tag=>counts.set(tag,(counts.get(tag)||0)+1)));el("topic-filters").innerHTML=[...counts.entries()].sort((a,b)=>b[1]-a[1]||a[0].localeCompare(b[0])).map(([tag,count])=>`<button type="button" class="topic-filter ${state.topics.has(tag)?"active":""}" data-topic="${safe(tag)}">${safe(tag)} · ${count}</button>`).join("");el("topic-filters").querySelectorAll("[data-topic]").forEach(button=>button.addEventListener("click",()=>{state.topics.has(button.dataset.topic)?state.topics.delete(button.dataset.topic):state.topics.add(button.dataset.topic);render()}))}
function renderList(){const questions=filtered();if(state.selectedId&&!state.questions.some(q=>q.id===state.selectedId))state.selectedId=questions[0]?.id||null;el("visible-count").textContent=questions.length;el("active-filter-label").textContent=state.topics.size?[...state.topics].join(" + "):state.stage==="All"?"All stages":state.stage;el("empty-list").classList.toggle("hidden",questions.length>0);el("question-list").innerHTML=questions.map(q=>{const done=state.completed.has(q.id),extra=q.tags.filter(tag=>!["Coding","Phone","Onsite","Low Level Design","System Design","MLE"].includes(tag)).slice(0,3);return`<button class="question-row ${done?"done":""} ${q.id===state.selectedId?"active":""}" type="button" data-id="${q.id}"><span class="row-status" data-status="${q.id}" role="checkbox" aria-checked="${done}" aria-label="${done?"Mark incomplete":"Mark complete"}">✓</span><span class="row-copy"><span class="row-title">${q.rank}. ${safe(q.title)}</span><span class="row-meta">${safe(q.lastReported)} · ${q.baseTags.includes("Phone")?"Phone":"Onsite"}</span><span class="row-tags">${extra.map(tag=>`<span class="tag ${/Design|LLD/.test(tag)?"design":""}">${safe(tag)}</span>`).join("")}</span></span><span class="frequency-pill">${q.frequency}%</span></button>`}).join("");el("question-list").querySelectorAll(".question-row").forEach(row=>row.addEventListener("click",event=>{const id=row.dataset.id;if(event.target.closest("[data-status]"))toggleDone(id);else selectQuestion(id)}))}
function selectQuestion(id){state.selectedId=id;history.replaceState(null,"",`#question=${id}`);render()}
function renderDetail(){const q=state.questions.find(item=>item.id===state.selectedId);el("detail-empty").classList.toggle("hidden",Boolean(q));el("detail-content").classList.toggle("hidden",!q);if(!q)return;el("detail-index").textContent=`Question ${q.rank} of ${state.questions.length}`;el("detail-title").textContent=q.title;el("detail-meta").innerHTML=`<span>${q.frequency}% frequency</span><span>•</span><span>Reported ${safe(q.lastReported)}</span>`;el("detail-tags").innerHTML=q.tags.map(tag=>`<span class="tag ${/Design|LLD/.test(tag)?"design":""}">${safe(tag)}</span>`).join("");el("detail-description").textContent=q.description;el("detail-source").href=q.url;updateDone(q.id);const questions=filtered(),index=questions.findIndex(item=>item.id===q.id);el("previous-question").disabled=index<=0;el("next-question").disabled=index<0||index>=questions.length-1}
function toggleDone(id){if(!id)return;const title=state.questions.find(item=>item.id===id)?.title||"Question";if(state.completed.has(id)){state.completed.delete(id);toast(`${title} moved back to practice`)}else{state.completed.add(id);toast(`${title} marked done`)}persistProgress();render()}
function persistProgress(){localStorage.setItem(STORAGE_KEY,JSON.stringify([...state.completed]))}
function updateDone(id){const done=state.completed.has(id);["detail-done-button","detail-done-footer"].forEach(key=>{const button=el(key);button.setAttribute("aria-pressed",String(done));button.classList.toggle("is-done",done);button.lastElementChild.textContent=done?"Completed":"Mark done"})}
function renderProgress(){const done=state.questions.filter(q=>state.completed.has(q.id)).length,total=state.questions.length,percent=total?Math.round(done/total*100):0;el("header-done-count").textContent=done;el("header-total-count").textContent=total;el("header-progress-bar").style.width=`${percent}%`;el("progress-percent").textContent=`${percent}%`;el("progress-bar").style.width=`${percent}%`;el("sidebar-done-count").textContent=done;el("sidebar-left-count").textContent=total-done;el("count-all").textContent=total;el("count-phone").textContent=state.questions.filter(q=>q.baseTags.includes("Phone")).length;el("count-onsite").textContent=state.questions.filter(q=>q.baseTags.includes("Onsite")).length}
function moveSelection(delta){const questions=filtered(),index=questions.findIndex(item=>item.id===state.selectedId),target=questions[index+delta];if(target)selectQuestion(target.id)}
function toast(message){el("toast").textContent=message;el("toast").classList.add("show");clearTimeout(toastTimer);toastTimer=setTimeout(()=>el("toast").classList.remove("show"),1800)}
function slugify(value){return value.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/(^-|-$)/g,"")}
function safe(value){return String(value).replace(/[&<>'"]/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"})[char])}
